/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2021 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdint.h>
#include <string.h> /* memset */
#include <unistd.h> /* close */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define __vo 				volatile

#define AHB1ENR				0x40023830U
#define APB2ENR				0x40023844U

/*
 * GPIO Macros
 */

#define GPIOA				0
#define GPIOA_MODER			0x40020000U
#define GPIOA_OSPEEDR		0x40020008U
#define GPIOA_PUPDR			0x4002000CU
#define GPIOA_PIN_NO 		0

#define GPIOD				3
#define GPIOD_MODER			0x40020C00U
#define GPIOD_OTYPER		0x40020C04U
#define GPIOD_OSPEEDR		0x40020C08U
#define GPIOD_ODR			0x40020C14U
#define GPIOD_PUPDR			0x4002000CU
#define GPIOD_PIN_NO 		12

/*
 * Interrupt Macros Peripheral Side
 */
#define EXTI_FT				0x40013C0CU
#define EXTI_IMR			0x40013C00U
#define EXTI_PR				0x40013C14U
#define SYSCFG_EXTICR1		0x40013808U

/*
 * Interrupt Macros Processor Side
 */
#define IRQ_NO_EXTI0 		6
#define NVIC_ISER0          ((__vo uint32_t*)0xE000E100)
#define NVIC_IPR1		 	((__vo uint32_t*)0xE000E404)

/*
 * General Macros
 */
#define ENABLE		1
#define RESET		0

void delay(void)
{
	for(int i = 0; i < 500000; i++);
}


int main(void)
{



	//enable peripheral clock for GPIOD & GPIOA
	uint32_t *ptr = (uint32_t *)AHB1ENR;
	*ptr |= (1 << GPIOD);
	*ptr |= (1 << GPIOA);

	//init board LED4 for output mode
	ptr = (uint32_t *)GPIOD_MODER;
	*ptr |= (1 << 2 * GPIOD_PIN_NO);

	//set LED4 output type as push-pull
	ptr = (uint32_t *)GPIOD_OTYPER;
	*ptr |= (0 << 2 * GPIOD_PIN_NO);

	//set LED4 speed as medium
	ptr = (uint32_t *)GPIOD_OSPEEDR;
	*ptr |= (0 << 2 * GPIOD_PIN_NO);

	//set LED4 speed as medium
	ptr = (uint32_t *)GPIOD_PUPDR;
	*ptr |= (0 << 2 * GPIOD_PIN_NO);

	uint32_t *Outputptr = (uint32_t *)GPIOD_ODR;
	*Outputptr |= (0 << 24);
	*Outputptr |= (0 << 25);

	//set User Button0 speed as medium
	uint32_t *Btnptr = (uint32_t *)GPIOA_OSPEEDR;
	*Btnptr |= (0 << 2 * GPIOA_PIN_NO);

	//no pull-up/pull-down needed for user button
	Btnptr = (uint32_t *)GPIOA_PUPDR;
	*Btnptr |= (0 << 2 * GPIOA_PIN_NO);

	//configure interrupt settings on peripheral side
	//enable falling edge interrupt on EXTI
	ptr = (uint32_t *)EXTI_FT;
	*ptr |= (1 << GPIOA_PIN_NO);

	//enable syscfg clock
	ptr = (uint32_t *)APB2ENR;
	*ptr |= (1 << 14);

	//enable GPIOA pin 0 interrupts from EXTI0
	ptr = (uint32_t *)SYSCFG_EXTICR1;
	uint8_t portcode = 0;
	*ptr |= (portcode << GPIOA_PIN_NO);

	//enable interrupt delivery
	ptr = (uint32_t *)EXTI_IMR;
	*ptr |= (1 << GPIOA_PIN_NO);

	ptr = (uint32_t *)GPIOD_ODR;
	*ptr |= ( 0 << GPIOD_PIN_NO);

	//configure interrupt settings on MCU side
	//enable IRQ 6 on NVIC which is connected to EXTI0
	*NVIC_ISER0 |= (1 << IRQ_NO_EXTI0);


	//set priortiy of IRQ number to 15
	*NVIC_IPR1 |= (15 <<  ((IRQ_NO_EXTI0 % 4) *8) +4 ) ;


}


void EXTI0_IRQHandler(void)
{
	uint32_t *ptr = (uint32_t *)EXTI_PR;
	uint32_t *Optr = (uint32_t *)GPIOD_ODR;
	delay();

	//clear the exti pr register corresponding to the pin number
	if(*ptr & ( 1 << 0))
	{
		//clear
		*ptr |= ( 1 << 0);
	}

	*Optr  ^= ( 1 << GPIOD_PIN_NO);

}


